const { DataTypes } = require('sequelize');
const sequelize = require('../utils/db');

const Vendor = sequelize.define('Vendor', {
  id: {
    type: DataTypes.INTEGER,
    primaryKey: true,
    autoIncrement: true,
  },
  vndel_delete_flag: DataTypes.STRING,
  vnco_company_number: DataTypes.STRING,
  vnvend_vendor_number: DataTypes.STRING,
  vnname_vendor_name: DataTypes.STRING,
  vnadd1_address_line1: DataTypes.STRING,
  vnadd2_address_line2: DataTypes.STRING,
  vnadd3_address_line3: DataTypes.STRING,
  vnadd4_address_line4: DataTypes.STRING,
  vnzip5_zip_code: DataTypes.STRING,
  vnzpx4_extra_zip: DataTypes.STRING,
  vnterm_terms_code: DataTypes.STRING,
  vnsort_alpha_sort_abbr: DataTypes.STRING,
  vnarea_area_code: DataTypes.STRING,
  vntele_telephone_number: DataTypes.STRING,
  vnlpay_last_payment_amount: DataTypes.DECIMAL(10, 2),
  vnlpdt_last_payment_date: DataTypes.DATEONLY,
  vnpytd_ytd_purchases: DataTypes.DECIMAL(10, 2),
  vnplyr_last_year_purchases: DataTypes.DECIMAL(10, 2),
  vndmtd_mtd_discounts: DataTypes.DECIMAL(10, 2),
  vndytd_ytd_discounts: DataTypes.DECIMAL(10, 2),
  vnovf_name_overflow: DataTypes.STRING,
  vngrrq_gal_rcpts_required: DataTypes.STRING,
  vnf001_filler: DataTypes.STRING,
  vnpbal_previous_balance: DataTypes.DECIMAL(10, 2),
  vnpurc_mtd_purchases: DataTypes.DECIMAL(10, 2),
  vnpay_mtd_payments: DataTypes.DECIMAL(10, 2),
  vncbal_current_balance: DataTypes.DECIMAL(10, 2),
  vnhold_hold_payments_vendor: DataTypes.STRING,
  vnsngl_single_check: DataTypes.STRING,
  vnty_dp_this_year_ytd_paid: DataTypes.DECIMAL(10, 2),
  vnly_dp_last_year_ytd_paid: DataTypes.DECIMAL(10, 2),
  vnexgl_expense_gl_sub: DataTypes.STRING,
  vn1099_ap1099_code: DataTypes.STRING,
  vnidno_1099_id_number: DataTypes.STRING,
  vnbox1_first_1099_box_number: DataTypes.STRING,
  vnbox2_second_1099_box_number: DataTypes.STRING,
  vnb2am_second_1099_box_amount: DataTypes.DECIMAL(10, 2),
  vnlpd8_last_payment_date: DataTypes.DATEONLY,
  vncai_d_carrier_id: DataTypes.STRING,
  vnpyn1_payee_name1: DataTypes.STRING,
  vnpyn2_payee_name2: DataTypes.STRING,
  vnnmct_irs_name_control: DataTypes.STRING,
  vnprid_adp_payroll_id: DataTypes.STRING,
  vnacls_ach_class: DataTypes.STRING,
  vnacos_ach_checking_or_savings: DataTypes.STRING,
  vnarte_ach_bank_routing_code: DataTypes.STRING,
  vnabk_ach_bank_account_number: DataTypes.STRING,
  vnfnam_first_name: DataTypes.STRING,
  vn_mnam_middle_name: DataTypes.STRING,
  vnlnam_business_last_name: DataTypes.STRING,
  vnsuff_name_suffix: DataTypes.STRING,
  vnctry_country_code: DataTypes.STRING,
  vncatg_category_code: DataTypes.STRING,
  vnf003_filler: DataTypes.STRING,
}, {
  tableName: 'apvend_vendormaster',
  timestamps: false,
});

module.exports = Vendor;
